# Generated by Django 3.1.6 on 2023-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('details', models.CharField(max_length=200)),
            ],
        ),
    ]
