# Generated by Django 3.1.6 on 2023-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='course1',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('details', models.CharField(max_length=200)),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
    ]
